class URL(object):
  root = 'https://www.instagram.com/'
  profile = 'https://www.instagram.com/%s'
  login = 'https://www.instagram.com/accounts/login/ajax/'
  logout = 'https://www.instagram.com/accounts/logout/'
  tag = 'https://www.instagram.com/explore/tags/'
  photo = 'https://www.instagram.com/p/'
  like = 'https://www.instagram.com/web/likes/%s/like/'
  unlike = 'https://www.instagram.com/web/likes/%s/unlike/'
  comment = 'https://www.instagram.com/web/comments/%s/add/'
  follow = 'https://www.instagram.com/web/friendships/%s/follow/'
  unfollow = 'https://www.instagram.com/web/friendships/%s/unfollow/'
  block = 'https://www.instagram.com/web/friendships/%s/block/'
  unblock = 'https://www.instagram.com/web/friendships/%s/unblock/'
